### ISSUE TITLE
Adding Scala.IO and Mix-IT

### ISSUE THREAD

**Issue by jeantil** [lauthieb/awesome-cfp#1]
Hello, 

I think the current list is missing out on 2 awesome conferences occurring in lyon : 
* https://scala.io (and https://cfp.scala.io which is open at the moment by the way :) )
* https://mixitconf.org/ (and https://mix-it.cfp.io)

what do you think, should I PR ?

**Comment by lauthieb** [comment]
Hello ! Yes you can make a PR for these conferences @ Lyon :)

**Comment by lauthieb** [comment]
Hello @jeantil !
@FabienPennequin has just added the Scala.io conference 2018 in this repo in its PR #4 :)
Feel free to add Mix-IT 🎉

**Comment by lauthieb** [comment]
Closes #5
